INSERT INTO TB_RACE (TB_RACE_RUNNER_CATEGORY, TB_RACE_CATEGORY, TB_RACE_DISTANCE_KM ) VALUES ('AMADOR', 'INICIANTE', 5);
INSERT INTO TB_RACE (TB_RACE_RUNNER_CATEGORY, TB_RACE_CATEGORY, TB_RACE_DISTANCE_KM ) VALUES ('AMADOR', 'INTERMEDIÁRIO', 10);
INSERT INTO TB_RACE (TB_RACE_RUNNER_CATEGORY, TB_RACE_CATEGORY, TB_RACE_DISTANCE_KM ) VALUES ('AMADOR', 'AVANÇADO', 24);
INSERT INTO TB_RACE (TB_RACE_RUNNER_CATEGORY, TB_RACE_CATEGORY, TB_RACE_DISTANCE_KM ) VALUES ('PROFISSIONAL', 'MEIA MARATONA', 21);
INSERT INTO TB_RACE (TB_RACE_RUNNER_CATEGORY, TB_RACE_CATEGORY, TB_RACE_DISTANCE_KM ) VALUES ('PROFISSIONAL', 'MARATONA', 42);
INSERT INTO TB_RACE (TB_RACE_RUNNER_CATEGORY, TB_RACE_CATEGORY, TB_RACE_DISTANCE_KM ) VALUES ('PROFISSIONAL', 'INICIANTE', 70);